module.exports = {
  "USER_ID":              "user_id",
  "USER_NAME":            "user_name",
  "NAME":                 "name",
  "GIVEN_NAME":           "given_name",
  "FAMILY_NAME":          "family_name",
  "EMAIL":                "email",
  "CLIENT_ID":            "client_id",
  "EXP":                  "exp",
  "AUTHORITIES":          "authorities",
  "SCOPE":                "scope",
  "JTI":                  "jti",
  "AUD":                  "aud",
  "SUB":                  "sub",
  "ISS":                  "iss",
  "IAT":                  "iat",
  "CID":                  "cid",
  "GRANT_TYPE":           "grant_type",
  "ADDITIONAL_AZ_ATTR":   "az_attr",
  "AZP":                  "azp",
  "AUTH_TIME":            "auth_time",
  "ZONE_ID":              "zid",
  "REVOCATION_SIGNATURE": "rev_sig"
};